language: node_js
addons:
  code_climate:
    repo_token: b91207ce6aad4842b397adedd46f7fcd4b7b324b9d6b32e9c3b2ee689da63b6a
node_js:
- '0.10'
script: gulp coverage
before_deploy:
  - gulp build
  - npm version ${TRAVIS_TAG} --no-git-tag-version
deploy:
  provider: npm
  email: andrewwaite@silktide.com
  on:
    tags: true
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
